BuiNguyenNgocHuy/TestUngDung/Areas/Admin/Controllers/QLNguoiDungController.cs
using ModelEF.Model;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestUngDung.Common;
using TestUngDung.DAO;
using PagedList;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class QLNguoiDungController : Controller
    {
        // GET: Admin/QLNguoiDung
        private BuiNguyenNgocHuyContext db = new BuiNguyenNgocHuyContext();
        public ActionResult Index(string searchString, int page = 1, int pageSize = 5)
        {
            var dao = new UserDao();
            var model = dao.ListAllPaging(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(model);
        }
            

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind(Include = "ID,UserName,Password,Status")] UserAccount userAccount)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (String.IsNullOrEmpty(userAccount.ID.ToString()))
                    {
                        return View();
                    }
                    var encryptedMd5Pas = Encryptor.MD5Hash(userAccount.Password);
                    userAccount.Password = encryptedMd5Pas;
                    db.UserAccounts.Add(userAccount);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("UserAccount", "Create-Post", ex.ToString());
            }
            return View();
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserAccount user = db.UserAccounts.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID = new SelectList("ID", "Name", "Password", "Status");
            return View(user);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserName,Password,Status")] UserAccount user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (String.IsNullOrEmpty(user.ID.ToString()))
                    {
                        return View();
                    }
                    BuiNguyenNgocHuyContext db = new BuiNguyenNgocHuyContext();
                    var encryptedMd5Pas = Encryptor.MD5Hash(user.Password);
                    user.Password = encryptedMd5Pas;
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("UserAccount", "Create-Post", ex.ToString());
            }
            return View();
        }
        ////////////
        // GET: Admin/QLNguoiDung/Delete/5
        public ActionResult Delete(int id)
        {
            var dao = new UserAccoutDao().Delete(id);
            return RedirectToAction("Index");
        }
    }
}

BuiNguyenNgocHuy/TestUngDung/Areas/Admin/Views/QLNguoiDung/Create.cshtml
@model  ModelEF.Model.UserAccount

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/Admin/QLNguoiDung/Index">Danh sách Người Dùng</a></li>
                        <li class="breadcrumb-item active">Thêm</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <div class="card card-primary">
        <div class="card-header" style="background-color:#ffc107;color:#1f2d3d">
            <h4 class="card-title">Thêm Người dùng </h4>
        </div>
        <form role="form">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.UserName, "Tài khoản", htmlAttributes: new { @class = "control-label col-md-5" })
                            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, "Mật khẩu", htmlAttributes: new { @class = "control-label col-md-5" })
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Status, "Status", htmlAttributes: new { @class = "control-label col-md-5" })
                            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
            </div>
            <div class="card-footer">
                &nbsp;&nbsp;<button type="submit" value="Create" class="btn btn-primary" onclick="Them1()"> <i class="fa fa-plus"></i>&nbsp;Thêm</button>
                <button class="btn alert-success">@Html.ActionLink("Quay Lại Danh Sách", "Index")</button>
            </div>
        </form>
    </div>
}
<script src="~/Scripts/jquery.validate.js"></script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function Them1() {
            alert('Bạn chắc chắn muốn Thêm?')
        }
    </script>
}
}

BuiNguyenNgocHuy/TestUngDung/Areas/Admin/Views/QLNguoiDung/Edit.cshtml
@model ModelEF.Model.UserAccount

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/Admin/QLDMDienthoai/Index">Danh Mục sản phẩm</a></li>
                        <li class="breadcrumb-item active">Sửa</li>
                    </ol>
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(model => model.ID)
                </div>
            </div>
        </div>
    </section>
    <div class="card card-primary">
        <div class="card-header" style="background-color:#ffc107;color:#1f2d3d">
            <h4 class="card-title">Sửa Sản Phẩm</h4>
        </div>
        <form role="form">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.UserName, "Tài khoản", htmlAttributes: new { @class = "control-label col-md-5" })
                            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, "Mật khẩu", htmlAttributes: new { @class = "control-label col-md-5" })
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Status, "Status", htmlAttributes: new { @class = "control-label col-md-5" })
                            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </div>

            <div class="card-footer">
                <div class="col-12 form-actions">
                    &nbsp;&nbsp;<button type="submit" value="Edit" class="btn btn-primary" onclick="Sua()"> <i class="fa fa-pencil"></i>&nbsp;Sửa</button>
                    <button class="btn alert-success">@Html.ActionLink("Quay Lại Danh Sách", "Index")</button>
                </div>
            </div>
        </form>

    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function Sua() {
            alert('Bạn chắc chắn muốn sửa?')
        }
    </script>
}

BuiNguyenNgocHuy/TestUngDung/Areas/Admin/Views/QLNguoiDung/Index.cshtml
@model PagedList.IPagedList<ModelEF.Model.UserAccount>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Assets/admin/css/sb-admin-2.min.css" rel="stylesheet" />
    <style>
        .ul.pagination {
            display: inline-block;
            padding: 0;
            margin: 0;
        }

        ul.pagination li {
            display: inline;
        }
                    ul.pagination li a {
                color: black;
                float: left;
                padding: 8px 16px;
                text-decoration: none;
                transition: background-color .3s;
            }

                ul.pagination li a.active {
                    background-color: #4CAF50;
                    color: white;
                }

                ul.pagination li a:hover:not(.active) {
                    background-color: #ddd;
                }
    </style>
</head>
<body>
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-8 text-gray-800">Danh sách người dùng</h1> 
        @using (Html.BeginForm("Index", "QLNguoiDung", FormMethod.Get))
        {
            <div class="row form-group">

                <div class="col-lg-12">
                    <div class="col-md-4">
                        <input type="text" value="@ViewBag.SearchString" class="form-control" name="searchString" />
                    </div>
                    <div class="col-md-4">
                        <button type="submit" class="btn btn-success">Tìm kiếm</button>
                    </div>
                </div>

            </div>}
        <a href="/Admin/QLNguoiDung/Create" class="btn btn-primary mb-2" style="color: white;background-color:#4e73df;border-color:#4e73df"><i class="fa fa-plus"></i>&nbsp; Thêm</a>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">

                <div class="table">
                    <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example" class="table table-bordered table-striped table-responsive" @*cellspacing="0"*@ @*role="grid"*@ @*aria-describedby="dataTable_info" style="width: 100%;"*@>
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 25%;">
                                                Mã Người dùng
                                            </th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 10%;">
                                                Tài khoản
                                            </th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 15%;">
                                                Mật khẩu
                                            </th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 15%;">
                                                Trạng thái
                                            </th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 15%;">
                                                Tác vụ
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model != null && Model.Count() > 0)
                                        {
                                            foreach (var item in Model)
                                            {
                                                <tr role="row" class="odd">
                                                    <td>@item.ID</td>
                                                    <td>@item.UserName</td>
                                                    <td>@item.Password</td>
                                                    <td><a href="#" class="btn-active" data-id="@item.ID"> @Html.Raw(item.Status ? "<strong>Kích hoạt</strong>" : "Khoá")</a></td>


                                                    @*<td>@item.pin</td>*@
                                                    <td>
                                                        @Html.ActionLink("Sửa", "Edit", new { id = item.ID }, new { @class = "btn btn-info", @title = "Chỉnh sửa" })

                                                        <div class="btn btn-warning" title="Xóa" , onclick="Xoa()">
                                                            &nbsp;
                                                            @Ajax.ActionLink("Xoá", "Delete", new { @id = item.ID }, new AjaxOptions
                                                       {
                                                           Confirm = "Bạn có muốn xoá " + @item.ID + "?",
                                                           OnComplete = "$('#row_" + @item.ID + "').remove()",
                                                           HttpMethod = "Delete"
                                                       })
                                                        </div>
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    </tbody>

                                </table>
                                <br />
                                <div>

                                    <div id="container" style="margin-left: 20px">
                                        <p></p>
                                        <p></p>
                                        <div class="pagination" style="margin-left: 400px">
                                            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                                            of @Model.PageCount  <br />
                                            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
                                        </div>
                                    </div>
                                </div>

                                <br />

                                <!-- Kết thúc -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Assets/admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Assets/admin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    @*<script>
        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>*@
    <script>
        function Xoa() {
            alert('Hãy cân nhắc cho việc xóa bản ghi?')
        }
    </script>
</body>

</html>